# This deployment will fetch the config from the configfile it is referencing.

# Apply:  kubectl apply -f k8s/configerror-deployment.yaml
# Run This to see the error : kubectl get pods -w
# Remove: kubectl delete -f k8s/configerror-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27170
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: DATABASE_URL
