# This deployment will hit CPU throttle once the service hits the cpu usage limit.

# Apply:  kubectl apply -f k8s/cputhrottle-deployment.yaml
# Remove: kubectl delete -f k8s/cputhrottle-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cputhrottle-service
  namespace: default
  labels:
    app: cputhrottle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cputhrottle-service
  template:
    metadata:
      labels:
        app: cputhrottle-service
    spec:
      containers:
        - name: cputhrottle-container
          image: hamshith/cpu_throttle:latest
          resources: 
            requests:
              cpu: "50m"
            limits:
              cpu: "50m"
